spring:
  cloud:
    gcp:
      spanner:
        instance-id: mk-db557
        database: users_db
        project-id: fair-myth-255211
        credentials:
          location: ${keyLocation:file:/Users/Dmytro_Melnychuk/Documents/configs/GCP/fair-myth-255211-12f20b20869a.json}
