spring:
  cloud:
    gcp:
      credentials:
        location: ${keyLocation:file:/Users/Denys_Smakovskyi/data-plateau-254915-bddf9a768c77.json}
      spanner:
#          location: ${keyLocation:file:/Users/Denys_Smakovskyi/data-plateau-254915-8f0e4e39f1fa.json}
