spring:
  cloud:
    gcp:
      spanner:
        project-id: ks-535
        instance-id: ks-local-dev
        database: db_users
        credentials:
          location: file:D:\gcp\keys\ks-535-bdaf96c28d30.json
      trace:
        credentials:
          location: file:D:\gcp\keys\ks-535-owner-c2600449e8fa.json
      logging:
        enabled: true
      credentials:
        location: file:D:\gcp\keys\ks-535-logs-writer.json
      project-id: ks-535
  sleuth:
    sampler:
      probability: 1.0

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
